import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../parts/odds_finder_dialog.dart';
import 'ai_second_explain_alert.dart';
import 'baganriki_brain_display_alert.dart';

class AiAnalysisExplainAlert extends ConsumerStatefulWidget {
  const AiAnalysisExplainAlert({super.key});

  @override
  ConsumerState<AiAnalysisExplainAlert> createState() => _AiAnalysisExplainAlertState();
}

class _AiAnalysisExplainAlertState extends ConsumerState<AiAnalysisExplainAlert> {
  static const List<String> _markdownContent = <String>[
      '## 使用AIについて',
      '',
      '当サービスのAI予想には、Anthropic社が開発した **Claude AI** を使用しています。',
      '',
      '---',
      '',
      '## どんな分析をしているの？',
      '',
      'レース発走の直前まで収集した **単勝・複勝オッズの動き** をもとに、AIが注目馬をピックアップしています。',
      '',
      '出走頭数に応じて、以下の頭数を選出します。',
      '',
      '- **8頭以下** → 4頭を選出',
      '- **9〜13頭** → 5頭を選出',
      '- **14頭以上** → 6頭を選出',
      '',
      'AIへの指示で最も重視しているのは **「当てること」ではなく「回収率を上げること」** です。1〜3番人気ばかりを選んで当てても低オッズのため回収率は上がりません。そのため **信頼度（来そうか）** と **妙味（そのオッズで買う価値があるか）** の2軸で馬を評価するよう指示しています。',
      '',
      '---',
      '',
      '## おすすめ度とは',
      '',
      '各選出馬には **おすすめ度**（100点満点）が付与されます。おすすめ度が高い順に表示されます。',
      '',
      'おすすめ度は以下の **2軸の合計** です。',
      '',
      '### 信頼度（60点分）— 来そうかどうか',
      '',
      '- 複勝オッズが継続的に下落している → 高評価',
      '- 断層の上側に位置している → 高評価',
      '- 単勝・複勝ともに資金流入が続いている → 高評価',
      '- 一時的な急落のみ・複勝が上昇傾向・断層の下側 → 低評価',
      '',
      '### 妙味（40点分）— そのオッズで買う価値があるか',
      '',
      '- 複勝 **1.5倍未満** → 5点以下（来ても儲からない）',
      '- 複勝 **1.5〜2.5倍** → 10〜20点',
      '- 複勝 **2.5〜4倍** → 20〜30点',
      '- 複勝 **4〜7倍** → 30〜38点',
      '- 複勝 **7倍以上かつ継続的な資金流入あり** → 38〜40点',
      '',
      '---',
      '',
      '## オッズ間断層とは',
      '',
      '人気順が隣り合う馬どうしのオッズの開きを表す指標です。',
      '',
      'この開きが大きい地点を「断層」と呼び、断層の手前にいる馬は市場から特別な支持を受けていると判断できます。**単勝断層** と **複勝断層** の両方を算出しており、同じ位置に断層が出ている場合は特に強いシグナルとして扱います。',
      '',
      '断層の位置・パターンに応じて、AIへの選出方針も変わります（下記「断層構造タイプ」参照）。',
      '',
      '---',
      '',
      '## 断層構造タイプとは',
      '',
      '断層の出方のパターンをシステムが自動判定し、AIへの選出方針として渡しています。',
      '',
      '- **タイプA**（二重断層・上位完結型）: 6番人気以内に断層が2か所以上 → 上位人気馬を中心に選出',
      '- **タイプB**（上位断層型）: 上位人気との間に断層が1か所 → 断層より上のグループを重視',
      '- **タイプC**（中間断層型）: 中位付近に断層 → 断層上側が本命・下側は穴候補',
      '- **タイプD**（断層なし・混戦型）: 断層なし → 複勝支持・変化率・6〜10番人気も均等に比較',
      '- **タイプE**（単複矛盾型）: 単勝と複勝で断層位置が食い違う → 複勝の継続的な動きを最優先',
      '',
      '---',
      '',
      '## OPIとは',
      '',
      '**OPI（Over Popularity Index）** は、今回のオッズが過去の同じ人気順の平均オッズと比べて高いか低いかを示す指標です。',
      '',
      '- **OPI > 1.2** → 過去より低いオッズ（市場が過大評価している可能性）→ 妙味が低い',
      '- **OPI < 0.8** → 過去より高いオッズ（市場が過小評価している可能性）→ 妙味がある',
      '',
      'AIへのおすすめ度算出の補正材料として活用しています。',
      '',
      '---',
      '',
      '## 推定確定オッズとは',
      '',
      '6分前オッズに**人気順位別の補正係数**を掛けて算出した「発走時点での最終オッズ予測値」です。過去の全レースから人気順位ごとに「6分前→確定オッズの変動パターン」を集計し、毎日更新しています。',
      '',
      '- **補正係数 < 1** → その人気順位の馬は直前にさらに人気が集中する傾向がある（見た目より確定オッズが下がりやすい）',
      '- **補正係数 > 1** → その人気順位の馬は直前に売れにくい傾向がある（見た目より確定オッズが上がりやすい）',
      '- **±誤差が大きい** → 予測の振れ幅が大きく、参考程度に留める',
      '',
      'AIへの妙味スコア計算では、6分前オッズそのままではなくこの**推定確定オッズを基準**に使うよう指示しています。',
      '',
      '---',
      '',
      '## 過去回収率（変化率帯別）とは',
      '',
      '「計測開始から6分前までにオッズがどれだけ動いたか（変化率帯）」と「人気帯」の組み合わせで、過去の**単勝回収率**を集計した指標です。',
      '',
      'たとえば「1〜3人気で10〜20%上昇（売られた）馬」の過去回収率が115%であれば、同じパターンの馬は長期的に利益が出ていることを意味します。',
      '',
      '- **変化率がマイナス（下落）** → 計測開始から6分前にかけて人気が集中し、オッズが下がった馬',
      '- **変化率がプラス（上昇）** → 計測開始から6分前にかけて人気が離れ、オッズが上がった馬',
      '',
      'AIへの参考情報として、各馬の変化率帯と人気帯の組み合わせに対応する**過去回収率・勝率・サンプル数**を渡しています。サンプル数が少ない場合は参考程度に留めます。',
      '',
      '---',
      '',
      '## OPI帯別回収率とは',
      '',
      '**OPI（Over Popularity Index）** の値を7つの帯に分類し、人気帯との組み合わせで過去の**単勝回収率**を集計した指標です。',
      '',
      'たとえば「OPI 1.50以上（大幅割安）× 4〜6人気」の過去回収率が130%であれば、市場が過小評価しているこのパターンは長期的に利益が出ていることを意味します。',
      '',
      '- **OPI 0.70未満** → 過去平均より大幅に低いオッズ（市場が強く過大評価・妙味なし）',
      '- **OPI 1.00〜1.15** → ほぼ適正水準',
      '- **OPI 1.50以上** → 過去平均より大幅に高いオッズ（市場が過小評価・妙味あり）',
      '',
      '変化率帯別回収率と合わせて使うことで、「今回の動きが過去の妙味パターンと一致しているか」をAIが多角的に判断できます。',
      '',
      '---',
      '',
      '## AIへの回収率データの使い方（重要）',
      '',
      'AIには「過去回収率・OPI帯別回収率は、**勝率ではなく回収率（%）を妙味スコアの最重要指標**として使うこと」を明示的に指示しています。',
      '',
      '- **回収率100%未満のパターン** → 勝率が高くても長期的には損をするパターン。妙味スコアを下げる材料として扱う',
      '- **回収率110%以上のパターン** → 積極的に妙味を高く評価する',
      '- **1〜3番人気ばかりの選出は禁止** → 低オッズ馬を並べるだけでは回収率が上がらないため、プロンプトで厳に制約している',
      '',
      '「当てること」ではなく「**長期的に回収率100%超えを狙うこと**」がこのシステムの目的です。',
      '',
      '---',
      '',
      '## 厳選穴レースとは',
      '',
      'AIが選出馬の中に **6〜10番人気の馬が含まれている** と判断した場合、そのレースを「厳選穴レース」とします。',
      '',
      'ただし、6番人気以内の隣接馬間に **断層が2個以上** ある場合は、上位人気馬の支配力が高いと判断し、厳選穴レースの対象から除外されます。',
      '',
      '---',
      '',
      '## 期待数値とは',
      '',
      '過去の似たようなレースで、同じ人気順の馬がつけていたオッズと今回を比べた指標です。',
      '',
      '「過去より今回のオッズが高め＝市場からやや軽視されているが、過去の同じ立場の馬は好走している」という観点で注目馬を絞り込んでいます。',
      '',
      '**なお、過去に似たレースが見つからない場合は、この指標が算出されないことがあります。**',
      '',
      '---',
      '',
      '## 過去のレース情報とは',
      '',
      '過去の出走履歴をAIに渡し、今回のレースの頭数に応じて有力馬を絞り込んだ指標です。',
      '',
      '頭数に応じた絞り込み基準は以下のとおりです。',
      '',
      '- **8頭以下** → 上位4頭に絞り込み',
      '- **9〜13頭** → 上位5頭に絞り込み',
      '- **14頭以上** → 上位6頭に絞り込み',
      '',
      '**なお、過去のレース情報が不十分な場合は、この指標が算出されないことがあります。**',
      '',
      '---',
      '',
      '## コース統計とは',
      '',
      '同じコース（距離・芝/ダート）での過去レースをもとに、単勝・複勝それぞれの回収率が高い人気順位を集計した統計です。',
      '',
      'たとえば「2番人気の単勝回収率が高い」という傾向があれば、今回の2番人気の馬を積極的に評価する根拠のひとつになります。AIへの分析でも、この統計と今回の人気順位を照らし合わせて予想するよう伝えています。',
      '',
      '**なお、統計データが存在しないコースの場合は、この情報はプロンプトに含まれません。**',
      '',
      '---',
      '',
      '## こんなプロンプトをAIに送っています',
      '',
      '```',
      'あなたは競馬オッズ分析の専門家です。',
      '有料公開するものなので、正しい日本語で返してください。',
      '',
      'レース情報',
      '日付: ●●●●-●●-●●',
      '開催: ●回●●●日',
      'レース: ●R ●●●●●●',
      '',
      '単勝・複勝オッズデータ（計測開始前〜発走6分前・全時点）',
      ' 1番(●人気) ○○○○○○',
      '  単勝: [計測前]●●.●→[21分]●●.●→[18分]●●.●→[15分]●●.●→[12分]●●.●→[ 9分]●●.●→[ 6分]●●.●倍（下落 ●●.●%）',
      '  複勝: 計測前●●.●-●●.●倍→6分前●●.●-●●.●倍（下落 ●●.●%）  単複比: ●.●倍',
      '  OPI: ●.●●（妙味あり）  ※●番人気の過去平均●.●倍÷現在●.●倍',
      '  推定確定オッズ: ●●.●倍（±●.●●）  ※6分前●●.●倍×補正係数●.●●●●',
      '  過去回収率（●〜●%下落 × ●〜●人気）: 回収率●●.●%  勝率●●.●%  サンプル●●件',
      '  OPI帯別回収率（OPI●.●●〜●.●● × ●〜●人気）: 回収率●●.●%  勝率●●.●%  サンプル●●件',
      ' 2番(●人気) ○○○○○○',
      '  単勝: [計測前]●●.●→...→[ 6分]●●.●倍（上昇 +●●.●%）',
      '  複勝: 計測前●●.●-●●.●倍→6分前●●.●-●●.●倍（上昇 +●●.●%）  単複比: ●.●倍',
      '  OPI: ●.●●（過剰人気）  ※●番人気の過去平均●.●倍÷現在●.●倍',
      '  推定確定オッズ: ●●.●倍（±●.●●）  ※6分前●●.●倍×補正係数●.●●●●',
      '  過去回収率（●〜●%上昇 × ●〜●人気）: 回収率●●.●%  勝率●●.●%  サンプル●●件',
      '  OPI帯別回収率（OPI●.●●〜●.●● × ●〜●人気）: 回収率●●.●%  勝率●●.●%  サンプル●●件',
      ' ...（出走頭数分続く）',
      '',
      '単勝断層テーブル（6分前単勝オッズ・隣接人気順間の比率）',
      '※比率が2.00以上の箇所を「断層あり」と判断しています',
      ' ●人気(●番)●●.●倍 → ●人気(●番)●●.●倍  比率: ●.●●  ★断層',
      '',
      '複勝断層テーブル（6分前複勝最小オッズ・隣接複勝人気順間の比率）',
      '※単勝断層と複勝断層が同じ位置に出ている場合は断層の信頼度が上がります',
      ' 複●位(●番)●.●倍 → 複●位(●番)●.●倍  比率: ●.●●  ★断層',
      '',
      '【断層構造タイプ（システム算出済み）】',
      'タイプ●：●●●●●●●●●●',
      '選出方針：●●●●●●●●●●',
      '',
      'なお、オッズ分析にあたり、下記の注目馬番も参考にしてください。',
      '①　オッズ間断層の調査から絞り込んだ馬番「●|●」',
      '②　期待数値の調査から絞り込んだ馬番「●|●|●」',
      '③　過去のレース情報から絞り込んだ馬番「●|●|●」',
      '',
      '【このシステムの目的（最重要）】',
      'このシステムの目的は「当てること」ではなく「回収率を上げること」です。',
      '「来そうかどうか（信頼度）」と「そのオッズで買う価値があるか（妙味）」を必ず両方考えてください。',
      '',
      'オッズ推移から注目馬を●頭選出してください。',
      '',
      '【おすすめ度の計算方法】',
      'おすすめ度は100点満点で、以下の2軸を合算して判断してください。',
      '■ 信頼度（60点分）: 複勝オッズの継続下落・断層上側・単複ともに流入継続 → 高評価',
      '■ 妙味（40点分）: 複勝1.5倍未満→5点以下 / 1.5〜2.5倍→10〜20点 /',
      '  2.5〜4倍→20〜30点 / 4〜7倍→30〜38点 / 7倍以上かつ継続流入→38〜40点',
      '',
      '分析の観点：',
      '・複勝オッズの動きを単勝より重視してください',
      '・単勝オッズ下落10%以上は人気急上昇として注目（一時的な急落は過大評価しない）',
      '・単複比が高い馬＝勝ちにくいが3着以内には絡みやすい',
      '・複勝の幅が広い馬＝市場の評価が割れている不安定な馬',
      '・複勝の幅が狭い馬＝安定して3着以内が期待されている馬',
      '・OPI>1.2は過去同人気より低オッズ（妙味低）、OPI<0.8は高オッズ（妙味高）',
      '・妙味スコアは6分前オッズではなく推定確定オッズを基準にする（±誤差が大きい馬は参考程度）',
      '',
      '選出馬は必ず以下の形式で●頭分出力してください。',
      '─────────────────────────────',
      '厳選穴レース|1または0',
      '馬番：●、馬名：○○○○○○、人気順: ●、6分前オッズ: ●●.●、おすすめ度: ●●、選出理由：〜〜〜〜〜〜〜〜（4〜5行の文章）',
      '─────────────────────────────',
      '```',
      '',
      '---',
      '',
      '## ご注意事項',
      '',
      '- AI予想はオッズの推移データのみを根拠とした参考情報です。馬の能力・騎手・馬場状態・血統などは考慮していません。',
      '- 予想が必ず的中することを保証するものではありません。',
      '- 馬券の購入はご自身の判断と責任のもとで行ってください。',
      '- 当サービスのAI予想はJRAおよびその関連団体とは一切関係ありません。',
  ];

  ///
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            _buildHeader(context),

            Divider(color: Colors.white.withValues(alpha: 0.5), thickness: 5),

            Row(
              children: <Widget>[
                Material(
                  color: Colors.transparent,
                  borderRadius: BorderRadius.circular(10),
                  child: InkWell(
                    onTap: () => OddsFinderDialog(context: context, widget: const BaganrikiBrainDisplayAlert()),
                    borderRadius: BorderRadius.circular(10),
                    splashColor: Colors.white.withValues(alpha: 0.35),
                    highlightColor: Colors.white.withValues(alpha: 0.1),
                    child: Container(
                      padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 10),
                      decoration: BoxDecoration(
                        border: Border.all(color: Colors.white),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: const Text(
                        'AI予想の判断基準について',
                        style: TextStyle(fontSize: 10, color: Colors.white, fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ),

                const SizedBox(width: 10),

                Material(
                  color: Colors.transparent,
                  borderRadius: BorderRadius.circular(10),
                  child: InkWell(
                    onTap: () => OddsFinderDialog(context: context, widget: const AiSecondExplainAlert()),
                    borderRadius: BorderRadius.circular(10),
                    splashColor: Colors.white.withValues(alpha: 0.35),
                    highlightColor: Colors.white.withValues(alpha: 0.1),
                    child: Container(
                      padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 10),
                      decoration: BoxDecoration(
                        border: Border.all(color: Colors.white),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: const Text(
                        '2nd AIの実行について',
                        style: TextStyle(fontSize: 10, color: Colors.white, fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ),
              ],
            ),

            Expanded(child: _buildBody()),
          ],
        ),
      ),
    );
  }

  ///
  Widget _buildHeader(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.fromLTRB(20, 16, 12, 0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text('AI予想について', style: TextStyle(color: Colors.white, fontSize: 12)),
          SizedBox.shrink(),
        ],
      ),
    );
  }

  ///
  Widget _buildBody() {
    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(20, 8, 20, 20),
      child: Container(
        margin: const EdgeInsets.all(3),
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(color: Colors.black.withValues(alpha: 0.5)),
        child: MarkdownBody(
          data: _markdownContent.join('\n'),
          styleSheet: MarkdownStyleSheet(
            h2: const TextStyle(fontSize: 13, color: Colors.greenAccent, fontWeight: FontWeight.bold),
            h3: const TextStyle(fontSize: 12, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
            p: const TextStyle(fontSize: 11, color: Colors.white),
            strong: const TextStyle(fontSize: 11, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
            listBullet: const TextStyle(fontSize: 11, color: Colors.white70),
            horizontalRuleDecoration: const BoxDecoration(
              border: Border(bottom: BorderSide(color: Colors.white24)),
            ),
            codeblockDecoration: BoxDecoration(
              color: Colors.black54,
              borderRadius: BorderRadius.circular(4),
              border: Border.all(color: Colors.white24),
            ),
            code: const TextStyle(fontSize: 10, color: Colors.white70, fontFamily: 'monospace'),
          ),
        ),
      ),
    );
  }
}
