import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AiSecondExplainAlert extends ConsumerWidget {
  const AiSecondExplainAlert({super.key});

  static const List<String> _markdownContent = <String>[
      '## 2nd AI（DeepSeek）とは',
      '',
      '「2nd AI」ボタンを押すと、中国のAI企業 **DeepSeek** が開発した **DeepSeek-V3** モデルが、',
      '1st AI（Claude）とは独立して同じレースを分析します。',
      '',
      '---',
      '',
      '## なぜ2つのAIを使うの？',
      '',
      '1st AIであるClaudeは非常に優秀ですが、どうしても **人気上位馬を中心にした堅実な予想** になりがちです。',
      'オッズの動きに忠実に従うあまり、ガチガチの本命サイドばかり選んでしまうことがあります。',
      '',
      'それ自体は間違いではありませんが、競馬の醍醐味は **穴馬の激走** にもあります。',
      '回収率を長期的に上げるためには、人気薄でもオッズ推移に根拠のある馬を拾えるかどうかが重要です。',
      '',
      'そこで2nd AIのDeepSeekには、少し違う視点を持ってもらっています。',
      '',
      '---',
      '',
      '## 2nd AIへの指示方針',
      '',
      '2nd AIのシステムプロンプトは次のとおりです。',
      '',
      '```',
      'あなたが受け取ったプロンプトには、1st AI（Claude）向けの厳格なルールがたくさん書かれています。',
      '「DB算出値を変更するな」「確率を自分で計算するな」「この数値に従え」——そういうルールです。',
      '',
      'しかし、それらは 1st AI を縛るための規則であり、あなたへの縛りではありません。',
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      'お前は自由に遊んでいい。ただし、真剣にやれ。',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '',
      '・OPI・断層タイプ・流入ランク——全部「参考情報」として扱っていい',
      '・回収率データも、信じるかどうかはあなた次第',
      '・おすすめ度の付け方に決まった計算式はない。あなた自身の感覚と論理で決めてください',
      '・1〜3番人気だろうが10番人気だろうが、あなたが「来る」と判断すれば選んでいい',
      '・データが示す方向とまったく逆の馬を選ぶことも、理由が語れるなら正しい',
      '',
      '1st AI が見落としそうな角度・異なる解釈・少数派の視点——それがあなたの存在価値です。',
      '「1st AIと同じ馬を同じ理由で選ぶ」のが最も価値のない回答です。',
      '',
      'フォーマットだけ守って、中身は大胆に。',
      '```',
      '',
      '1st AIが「回収率データに基づく厳密な評価」重視なのに対し、2nd AIは **「根拠ある遊び・独自の読み」** を全面的に許容しています。波乱度・下位進入度・大穴進入度の3指標も、2nd AI自身の判断で自由に数値を設定できます。',
      '',
      '---',
      '',
      '## 使用するデータ',
      '',
      '2nd AIは1st AIとは**完全に独立**しており、1st AIが実行済みかどうかに関係なく動作します。プロンプトはDBから自前で生成するため、1st AIの結果に依存しない仕組みになっています。',
      '',
      '分析に使うデータは1st AIとほぼ同じ構成です。',
      '',
      '- 単勝・複勝オッズの推移',
      '- 断層構造タイプ（システムが自動算出）',
      '- OPI（過去オッズ比較指数）・推定確定オッズ',
      '- 過去のレース情報・コース統計',
      '- 過去回収率・OPI帯別回収率・フェーズパターン別回収率（数値データ）',
      '',
      '2nd AIもフォーマットに従い、出力の2行目に **波乱度・下位進入度・大穴進入度**（各1〜5）を出力します。これはアプリ画面に1st AIと同じ形式で表示されます。',
      '',
      'ただし、以下は意図的に除外して送信しています：',
      '',
      '- **厳選穴レース判定のロジック** — 2nd AI独自の穴馬視点を優先するため',
      '- **回収率データの「使い方指示」** — 数値は渡すが「こう使え」という縛りは外す',
      '- **おすすめ度の固定計算式**（60点信頼度＋40点妙味） — 自由な評価軸を許容するため',
      '- **「このシステムの目的は回収率を上げること」という目的指示** — 当てにいっても構わない',
      '',
      '---',
      '',
      '## 補欠とは',
      '',
      '2nd AIが選んだ馬のうち、**1st AI（Claude）が選んでいない馬**を「補欠」と表示しています。',
      '',
      '- 両AIが共通して選んだ馬 → メインリストに **緑枠の「2nd AI理由」** を追加表示',
      '- 2nd AIのみが選んだ馬 → リスト下部に **「補欠」バッジ付き** で別表示',
      '',
      '補欠馬はClaudeの評価では惜しくも外れた馬ですが、DeepSeekの視点では根拠のある注目馬です。',
      '本命サイドが物足りないと感じたときに、補欠馬を加えた馬券を検討する材料としてご活用ください。',
      '',
      '---',
      '',
      '## 「補欠でX頭をカバー」とは',
      '',
      'レース結果が出たあと、1st AIが完全には当てられなかったレースで、',
      '**補欠馬が実際の1〜3着に入っていた場合**に「補欠でX頭をカバー」と表示されます。',
      '',
      'これは「2nd AIの補欠馬も買い目に加えていれば、あとX頭カバーできた」という振り返り指標です。',
      '',
      '---',
      '',
      '## 結果の見方',
      '',
      '合致結果の表示は以下のように読みます。',
      '',
      '- **ピンク表示**：1st AIだけで3頭カバー、または補欠込みで合計3頭カバー',
      '- **黄色表示**：払戻が高額（三連複1万円以上）',
      '- **「+X」**（緑）：1st AIの合致数に加えて、補欠がさらにX頭カバーしたことを示す',
      '',
      '---',
      '',
      '## キャッシュについて',
      '',
      '2nd AIの分析結果は **サーバー側にキャッシュ**されます。',
      '同じレースに対して2回目以降に「2nd AI」ボタンを押した場合は、',
      'DeepSeek APIへの通信は発生せず、保存済みの結果が即座に返ります。',
      '',
      '---',
      '',
      '## ご注意事項',
      '',
      '- 2nd AIはあくまで参考情報です。必ず的中することを保証するものではありません。',
      '- 2nd AIの分析もオッズ推移データのみに基づいており、馬の能力・騎手・馬場などは考慮していません。',
      '- 馬券の購入はご自身の判断と責任のもとで行ってください。',
  ];

  ///
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.fromLTRB(20, 16, 12, 0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Text('2nd AI（DeepSeek）について', style: TextStyle(color: Colors.white, fontSize: 12)),
                  SizedBox.shrink(),
                ],
              ),
            ),

            Divider(color: Colors.white.withValues(alpha: 0.5), thickness: 5),

            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 20),
                child: Container(
                  margin: const EdgeInsets.all(3),
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(color: Colors.black.withValues(alpha: 0.5)),
                  child: MarkdownBody(
                    data: _markdownContent.join('\n'),
                    styleSheet: MarkdownStyleSheet(
                      h2: const TextStyle(fontSize: 13, color: Colors.greenAccent, fontWeight: FontWeight.bold),
                      h3: const TextStyle(fontSize: 12, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
                      p: const TextStyle(fontSize: 11, color: Colors.white),
                      strong: const TextStyle(fontSize: 11, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
                      listBullet: const TextStyle(fontSize: 11, color: Colors.white70),
                      horizontalRuleDecoration: const BoxDecoration(
                        border: Border(bottom: BorderSide(color: Colors.white24)),
                      ),
                      codeblockDecoration: BoxDecoration(
                        color: Colors.black54,
                        borderRadius: BorderRadius.circular(4),
                        border: Border.all(color: Colors.white24),
                      ),
                      code: const TextStyle(fontSize: 10, color: Colors.white70, fontFamily: 'monospace'),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
