import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AiSecondExplainAlert extends ConsumerWidget {
  const AiSecondExplainAlert({super.key});

  static const List<String> _markdownContent = <String>[
      '## 2nd AI（DeepSeek）とは',
      '',
      '「2nd AI」ボタンを押すと、DeepSeek社の **DeepSeek-V3** というAIが、1st AI（Claude）とは別に、同じレースをもう一度分析します。',
      '',
      '実は、1st AIの予想が終わるとすぐに、裏側で2nd AIの分析も始めています。そのため、ボタンを押した時点で、ほとんどの場合はすでに結果ができあがっています。',
      '',
      '---',
      '',
      '## なぜ2つのAIを使うの？',
      '',
      '1st AIのClaudeはとても優秀ですが、ルールにきっちり従うぶん、**人気上位の馬を中心とした手堅い予想** になりがちです。',
      '',
      'それ自体は間違いではありません。でも、競馬の醍醐味は **人気薄の激走** にもあります。回収率を上げるには、人気がなくても「お金の動きに根拠がある馬」を拾えるかどうかが大切です。',
      '',
      'そこで2nd AIには、**同じデータを、自分の目で、別の角度から見てもらう** 役割をお願いしています。',
      '',
      'いわば、同じ新聞を読んだ2人の予想家に、それぞれ印を打ってもらうイメージです。',
      '',
      '---',
      '',
      '## 2nd AIへのメッセージ',
      '',
      '2nd AIには、次のようなメッセージを伝えています（一部抜粋）。',
      '',
      '```',
      'あなたの仕事は、1st AIの分析を確認することではなく、',
      '「自分の目で同じデータを見て、自分の答えを出す」ことです。',
      '',
      '──────────────────────────────',
      'お前は自由に遊んでいい。ただし、真剣にやれ。',
      '──────────────────────────────',
      '',
      '1〜3番人気だろうが10番人気だろうが、',
      'あなたが「来る」と判断すれば選んでいい。',
      'ただし、根拠のない逆張りは禁止。',
      '',
      '1st AIとの不一致を目的にしてはいけません。',
      '同じ馬を高く評価したなら、そのまま選んでください。',
      '',
      'フォーマットだけ守って、中身は大胆に。',
      '```',
      '',
      'ポイントは、**「1st AIと違う馬を選べ」とは言っていない** ことです。お願いしているのは、あくまで「自分の目で、正直に評価すること」。その結果、1st AIと同じ馬を選ぶのも、別の馬を選ぶのも自由です。',
      '',
      '---',
      '',
      '## 自由といっても、守るルールは同じ',
      '',
      '2nd AIにも、1st AIと同じ大事なルールを守らせています。',
      '',
      '- **「当てる」より「回収率」** を最優先にする',
      '- おすすめ度は1st AIと同じく **信頼度60点＋妙味40点** の配分で採点する',
      '- 人気順・レースのタイプ・人気の過熱度（OPI）など、**システムが計算した数字は書き換えない**',
      '- 発走後にしか分からない情報（確定オッズや結果など）は使わない',
      '- 配当が安すぎる馬や、基準点に届かない馬は選ばない',
      '',
      '自由なのは、**データをどう読むか、どこを重く見るか** の部分です。',
      '',
      '---',
      '',
      '## 2nd AIも馬の実力をチェックします',
      '',
      '2nd AIも、各馬の近走成績（最大10走）から、実力と今回の条件への向き不向きを100点満点で採点します。',
      '',
      '- 地力・これまで走ってきたクラス（25点）',
      '- 最近のレース内容・着差・相手関係（20点）',
      '- コース・距離・芝／ダート・馬場への適性（20点）',
      '- 脚質・展開・枠順との相性（15点）',
      '- 末脚・位置取り・レースぶり（10点）',
      '- 斤量・騎手・馬体重・レース間隔など（10点）',
      '',
      '結果は **A（80点以上）／B（70点台）／C（60点台）／D（59点以下）** の4段階で、選出理由の最初に「能力適性:A（84点）。」のように書かれています。',
      '',
      '---',
      '',
      '## 2nd AIが見ているデータ',
      '',
      '2nd AIは1st AIの予想結果を **見ていません**。完全に別々に分析しています。',
      '',
      '渡しているデータは、1st AIとほぼ同じです。',
      '',
      '- 単勝・複勝オッズの動き（計測開始前〜発走6分前）',
      '- オッズの壁（断層）とレースのタイプ',
      '- 人気の過熱度（OPI）・最終オッズの予測',
      '- 流入ランク・直前の勢い・似たレースの成績',
      '- 3つの過去回収率',
      '- 各馬の近走成績と今回の条件',
      '',
      'ただし、次の2つは2nd AIには頼んでいません。',
      '',
      '- **厳選穴レースの判定** — 2nd AIには、先入観なしで穴馬を探してもらうため',
      '- **波乱度・下位進入度・大穴進入度** — この3つは1st AIの判定を使うため',
      '',
      '2nd AIが選ぶのは **最大5頭** です。基準を満たす馬がいなければ、選ばないこともあります。',
      '',
      '---',
      '',
      '## 2つのAIの予想のまとめ方',
      '',
      '2nd AIボタンを押すと、2つのAIの予想をシステムが自動でまとめて、**おすすめ度の高い順に1つのリスト** にして表示します。',
      '',
      '### 両方のAIが選んだ馬',
      '',
      '別々に考えた2つのAIが同じ結論にたどり着いた、ということなので、**信頼できる材料** として扱います。',
      '',
      'おすすめ度は **2つのAIの平均＋5点**（最大100点）になります。',
      '',
      '### 選出理由の見分け方',
      '',
      '選出理由には、その馬を選んだAIの文章をそのまま載せています。**2nd AIが書いた文章は枠で囲んで** 表示しているので、両方のAIが選んだ馬は「枠なしの文章（1st AI）」と「枠つきの文章（2nd AI）」が並びます。',
      '',
      '---',
      '',
      '## 2nd AIだけが選んだ馬は？',
      '',
      '2nd AIだけが選んだ馬は、そのまま表示されるわけではありません。**2nd AIのひらめきだけで決まらないよう**、システムが客観的なデータでもう一度確認します。',
      '',
      '採用されるのは、**おすすめ度70点以上**（タイプAのレースは80点以上）で、さらに次のうち **2つ以上** に当てはまる馬です。',
      '',
      '- 単勝の人気より、複勝の人気のほうが2つ以上高い',
      '- 人気の近い馬どうしの中で、複勝にいちばん（または2番目に）お金が入っている',
      '- 7番人気以下で、発走直前に単勝・複勝ともに買われている',
      '- 似たレースで、同じ人気の馬が5着以内に入った割合が7割以上',
      '- 最終オッズの予測で見て、過去の同じ人気の馬より割安',
      '- 同じパターンの馬を過去に買い続けたら、回収率110%以上だった',
      '',
      '採用できる数は、レースのタイプによって変わります。',
      '',
      '- **タイプA（上位で決まりそう）** → 原則0頭。とくに根拠がそろった馬だけ1頭',
      '- **タイプB・C** → 最大1頭',
      '- **タイプD・E（混戦・判断が難しい）** → 最大2頭',
      '',
      '荒れそうなレースほど、2nd AIの独自の視点を多めに取り入れる仕組みです。',
      '',
      '表示枠がすでにいっぱいの場合は、リストでいちばん点数の低い馬と比べて、上回っていれば入れ替わります。',
      '',
      '最後に、2つのAIをまとめたリスト全体に対して、基準点・配当が安すぎないか・過去の回収率などのチェックをもう一度かけ、最終的な並びが決まります。',
      '',
      'ここを通った馬は、1st AIが選んだ馬とまったく同じ扱いで並びます。「1st AIが見落としたかもしれない馬」として、ぜひ参考にしてください。',
      '',
      '---',
      '',
      '## 結果の見方',
      '',
      'レース後に表示される「合致結果」の数字は、**画面に並んでいる馬のうち、何頭が3着以内に入ったか** です。どちらのAIが選んだかは区別していません。',
      '',
      '- **ピンク表示**：3頭以上が3着以内に入った',
      '- **黄色表示**：高配当（三連複1万円以上）',
      '',
      '---',
      '',
      '## AIがうまく答えられなかったときは',
      '',
      '- **1st AIがうまく答えられなかった場合** → そのレースの予想は表示しません。2nd AIだけの予想を、通常の予想として出すことはありません。',
      '- **2nd AIがうまく答えられなかった場合** → 1st AIだけの予想をそのまま表示します。',
      '',
      '---',
      '',
      '## 2回目以降はすぐに表示されます',
      '',
      '2nd AIの分析結果は保存しているので、同じレースで2回目以降にボタンを押したときは、すぐに結果が表示されます。',
      '',
      '万が一、保存した結果が壊れていた場合は、自動的に分析をやり直します。',
      '',
      '---',
      '',
      '## ご注意',
      '',
      '- 2nd AIの予想も **参考情報** です。的中を保証するものではありません。',
      '- 2nd AIも、オッズの動きと過去の成績をもとに分析しています。当日の馬場状態・パドック・返し馬・血統などは考慮していません。',
      '- 馬券の購入は、ご自身の判断と責任でお楽しみください。',
  ];

  ///
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.fromLTRB(20, 16, 12, 0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Text('2nd AI（DeepSeek）について', style: TextStyle(color: Colors.white, fontSize: 12)),
                  SizedBox.shrink(),
                ],
              ),
            ),

            Divider(color: Colors.white.withValues(alpha: 0.5), thickness: 5),

            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 20),
                child: Container(
                  margin: const EdgeInsets.all(3),
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(color: Colors.black.withValues(alpha: 0.5)),
                  child: MarkdownBody(
                    data: _markdownContent.join('\n'),
                    styleSheet: MarkdownStyleSheet(
                      h2: const TextStyle(fontSize: 13, color: Colors.greenAccent, fontWeight: FontWeight.bold),
                      h3: const TextStyle(fontSize: 12, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
                      p: const TextStyle(fontSize: 11, color: Colors.white),
                      strong: const TextStyle(fontSize: 11, color: Colors.yellowAccent, fontWeight: FontWeight.bold),
                      listBullet: const TextStyle(fontSize: 11, color: Colors.white70),
                      horizontalRuleDecoration: const BoxDecoration(
                        border: Border(bottom: BorderSide(color: Colors.white24)),
                      ),
                      codeblockDecoration: BoxDecoration(
                        color: Colors.black54,
                        borderRadius: BorderRadius.circular(4),
                        border: Border.all(color: Colors.white24),
                      ),
                      code: const TextStyle(fontSize: 10, color: Colors.white70, fontFamily: 'monospace'),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
